version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      discovery.type: single-node
